# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

networks:
    inventory-mgt-system-api-net:

services: 
    inventory-mgt-system-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: inventory-mgt-system-api
        restart: always
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - inventory-mgt-system-api-net
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s

    sql-server:
        image: mcr.microsoft.com/mssql/server
        container_name: sql-server
        environment:
            SA_PASSWORD: "DEV@12345"
            ACCEPT_EULA: "Y"
        networks:
            - inventory-mgt-system-api-net

